name: Fetch RBTVPlus Streams Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Her gün gece yarısı
  workflow_dispatch:  # Manuel çalıştırma için

jobs:
  fetch-streams:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Run RBTVPlus Stream Fetcher
      run: python rbtvplus_stream_fetcher.py
      
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add streams/*.m3u
        git commit -m "Auto-update: RBTVPlus streams $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
        git push
