name: Golvar2693 M3U Playlist Generator

on:
  workflow_dispatch:  # Manuel çalıştırma için
  schedule:
    - cron: '0 */4 * * *'  # Her 4 saatte bir
  push:
    branches: [ main ]

jobs:
  generate-playlist:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Golvar2693 M3U Generator
      run: python golvar2693.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add golvar2693.m3u
        
        # Değişiklikleri kontrol et ve commit et
        if ! git diff --staged --quiet; then
          git commit -m "🤖 Auto-update Golvar2693 playlist - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
          echo "Playlist güncellendi ve push edildi."
        else
          echo "Değişiklik yok, commit atlanıyor."
        fi

    - name: Upload M3U as artifact
      uses: actions/upload-artifact@v4
      with:
        name: golvar2693-playlist
        path: golvar2693.m3u
        retention-days: 1
