name: Daily Stream Scraper

on:
  schedule:
    - cron: '0 6,12,18 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code with full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Tüm git history'yi çek
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      run: python main.py
        
    - name: List generated files
      run: ls -la
      
    - name: Check M3U file content
      run: |
        if [ -f streams.m3u ]; then
          echo "M3U File Content:"
          head -10 streams.m3u
          echo "Total lines: $(wc -l < streams.m3u)"
        else
          echo "M3U file not found"
        fi
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Pull latest changes before push
      run: |
        git pull origin main --rebase --allow-unrelated-histories
        
    - name: Commit and push changes
      run: |
        git add streams_data.json streams.m3u
        # Değişiklik olup olmadığını kontrol et
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update: M3U streams playlist - $(date +'%Y-%m-%d %H:%M')"
          git push origin main
        fi
