name: Update Solh TV M3U

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Commit/push için gerekli
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Tüm commit geçmişini al
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests
        
    - name: Run scraper
      id: scrape
      run: |
        python scrape_solh_tv.py
        echo "SCRAPE_DATE=$(date)" >> $GITHUB_OUTPUT
        
    - name: Commit and push if changed
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add solh-tv.m3u
        git diff --cached --quiet || (git commit -m "Auto-update M3U file [skip ci]" && git push)
