name: TRT Playlist Otomatik Güncelleme

on:
  schedule:
    - cron: "0 */3 * * *" # Her 3 saatte bir
  workflow_dispatch: # Manuel çalıştırma

jobs:
  update-trt-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Repo'yu Klonla
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Bağımlılıkları Kur
        run: |
          pip install requests

      - name: TRT Playlist Script Çalıştır
        run: |
          python trt_playlist_creator.py

      - name: Playlist'i Commit Et
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add trt_playlist.m3u
          git commit -m "Otomatik güncelleme: $(date '+%Y-%m-%d %H:%M:%S')" || echo "Değişiklik yok"
          git push
