name: Update Pars TV Stream

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı çalışacak
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false  # Bu önemli!
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Get stream URL
      run: python get_stream.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add parsatv.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Pars TV stream" && git push)
