name: Update M3U Playlist Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Her gün UTC 00:00'da çalıştır
  workflow_dispatch:       # Manuel çalıştırma seçeneği

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run playlist creator
      run: python trt_playlist_creator.py -o trt_playlist.m3u -q

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add trt_playlist.m3u
        git diff --quiet && git diff --staged --quiet || git commit -m "Update playlist - $(date)"
        git push
