name: Update Solh TV M3U

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Commit/push için gerekli izin
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install beautifulsoup4 requests
        
    - name: Run scraper and create M3U
      run: |
        python scrape_solh_tv.py
        cat solh-tv.m3u  # İçeriği loglarda görüntüle
        
    - name: Commit changes
      if: always()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add solh-tv.m3u
        git commit -m "Auto-update M3U" || echo "No changes to commit"
        
    - name: Push changes
      run: git push
